import pygame
import numpy as np

WITH_SENSORS = True
DRAW_SENSORS = True
IS_WINDOW_FOLLOW_Y = False

HUMAN_PLAYER = True

TILE_HEIGHT = 20
TILE_WIDTH = 20
TILES_COUNT_X = 0
TILES_COUNT_Y = 0

SENSOR_WIDTH = 10
SENSOR_HEIGHT = 10
SENSOR_UP_LINES = 5
SENSOR_DOWN_LINES = 5
SENSOR_LEFT_LINES = 5
SENSOR_RIGHT_LINES = 5

SENSOR_MAX_DISTANCE_COL_CHECK = 350

PLAYER_HEIGHT = 3 * TILE_HEIGHT
PLAYER_WIDTH = 2 * TILE_WIDTH

PLAYER_WIDTH_COUNT_SENSORS = 1
PLAYER_HEIGHT_COUNT_SENSORS = 1
WIDTH_SPACES_SIZE = 15
HEIGHT_SPACES_SIZE = 20

SENSOR_MATRIX_LINES = SENSOR_UP_LINES + PLAYER_HEIGHT_COUNT_SENSORS + SENSOR_DOWN_LINES
SENSOR_MATRIX_COLUMNS = SENSOR_LEFT_LINES + PLAYER_WIDTH_COUNT_SENSORS + SENSOR_RIGHT_LINES


WINDOW_WIDTH = 1000
WINDOW_HEIGHT = TILE_HEIGHT * TILES_COUNT_Y

PLAYER_BACK_OFFSET = WINDOW_WIDTH / 2 - WINDOW_WIDTH / 10
PLAYER_UP_OFFSET = WINDOW_HEIGHT / 2


TICK_RATE = 100

PLAYER_MOVEMENT_SPEED = 5
# PLAYER_JUMP_POWER = 40
PLAYER_MOMENTUM_STEP = 0.6


ENEMY_MOVEMENT_SPEED = 20

GRAVITY = 15

